spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/interviewos
spring.datasource.username=interviewos
spring.datasource.password=devpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
jwt.secret=iamagoodmanwithaiexpertise
jwt.expiration-ms=86400000